export const copy = {
  ja: {
    skip: "本文へスキップ",
    nav: ["ためす", "文字見本", "つかう"],
    free: "気まぐれな文字たちの、小さな見本帳。",
    hero: ["文字にも、", "ねこごころ。"],
    intro:
      "まあるい輪郭に、ちいさな耳。\nときどき、しっぽ。\nいつもの言葉が、ちょっとなつっこくなるフォント。",
    try: "好きな言葉で、ためす",
    download: "フォントをダウンロード",
    heroNote: "にくきゅう丸 / NIKUKYU MARU",
    stamp: ["商用利用も", "どうぞ。"],
    ribbon: ["まるい。", "やわらかい。", "ちょっと、ねこ。"],
    playground: "ことばを、なでてみる。",
    playDesc: "好きな文字を入力して、あなただけの表情を見つけて。",
    input: "試し書きする文字",
    presets: ["ねこのいる暮らし", "CAT & coffee", "ひらがな"],
    samples: [
      "ねこと、ひとやすみ。\nCAT & nap",
      "Cozy cat cafe\nA little purr, a little joy.",
      "にくきゅうまる\nあいうえお かきくけこ",
    ],
    size: "文字の大きさ",
    spacing: "文字のあいだ",
    color: "インクの色",
    colors: ["こげ茶", "朱色", "深緑"],
    alternates: "「こ」「る」に肉球を",
    reset: "もとにもどす",
    privacy: "入力した文字はブラウザー内だけで処理します。",
    empty: "ここに、好きなことばを。",
    missing: "このフォントにない文字（別の書体で表示されます）：",
    features: [
      "耳は、ちょこんと。",
      "しっぽは、気ままに。",
      "肉球も、ひっそり。",
    ],
    featureDescriptions: [
      "太くまるい骨格と、幅広い猫耳。文字のかたちから猫らしく。",
      "文字の終わりが、くるり。ひと文字ずつ違う表情をどうぞ。",
      "a の内側や「こ」「る」の異体字に、小さな足あとを。",
    ],
    glyphTitle: "ひと文字ずつ、ねこ模様。",
    glyphDesc: "英字も、かなも、漢字も。見出しに使える7,516文字を収録。",
    categories: ["英字", "ひらがな", "カタカナ", "漢字", "その他", "すべて"],
    search: "収録文字を探す",
    searchPlaceholder: "文字を入力：ね A 猫",
    noGlyph: "一致する収録文字は見つかりませんでした。",
    more: "さらに表示",
    shown: "文字を表示",
    allChars: "全収録文字を見る",
    usesTitle: "そのことばに、ひとさじの愛嬌。",
    usesDesc:
      "カフェのメニュー、パッケージ、イベントの見出し。大きく使うと、猫らしさがよく見えます。",
    useLabels: ["01 / MENU", "02 / PACKAGE", "03 / POSTER"],
    storyLabel: "THE MAKING OF",
    storyTitle: "絵の中の文字が、\n使えるフォントになるまで。",
    story:
      "画像生成で描いた猫の英字を、ひと文字ずつ曲線に。実際のフォントと見本を並べて、耳、しっぽ、丸みを整えました。日本語は Mochiy Pop One と Zen Maru Gothic を土台にしています。",
    storyLink: "生成見本とフォントを見比べる",
    downloadTitle: "あなたのことばにも、\nねこごころを。",
    downloadDesc: "無料でダウンロード。個人でも、お仕事でも。",
    formats: ["パソコンで使う", "Webサイトで使う", "編集・制作に使う"],
    formatDesc: [
      "Windows・macOSにインストールするフォント。",
      "サイトに埋め込むための軽量なWebフォント。",
      "UFOソース・参照画像・検証記録をまとめたZIP。",
    ],
    howTitle: "つかう前に、ちょっとだけ。",
    faqs: [
      [
        "インストールするには？",
        "TTFをダウンロードして開き、Windowsでは「インストール」、macOSではFont Bookで追加します。使用中のアプリは一度開き直してください。",
      ],
      [
        "商用利用はできますか？",
        "はい。SIL Open Font License 1.1で公開しています。制作物の商用利用やWeb埋め込みができます。フォントそのものの単体販売はできません。フォントを再配布するときは著作権表示とライセンスを同梱してください。",
      ],
      [
        "おすすめの使い方は？",
        "太い横組みの見出し向けです。耳や肉球を楽しむには32px以上を目安に。小さな本文や縦組みには向きません。カーニング・ヒンティング・縦組み専用メトリクスは未実装です。",
      ],
      [
        "Webに組み込むには？",
        "WOFF2をサイトに配置し、下のCSSを使ってください。font-weightは800。「こ」「る」の肉球付き異体字はss01で切り替えられます。",
      ],
    ],
    copyCss: "CSSをコピー",
    copied: "コピーしました",
    copyFail: "コピーできませんでした。コードを選択してコピーしてください。",
    license: "ライセンス全文",
    source: "ソースと制作記録",
    footer: "まるい文字で、まるい一日を。",
    loading: "フォントを読み込んでいます…",
    failed: "フォントを読み込めませんでした。ページを再読み込みしてください。",
    metadataFailed:
      "収録文字一覧を読み込めませんでした。再読み込みをお試しください。",
    back: "トップへ",
    unavailable: "ページが見つかりません",
    errorText: "そのページは、ねこがどこかへ持っていったようです。",
  },
  en: {
    skip: "Skip to content",
    nav: ["Try it", "Characters", "Download"],
    free: "A little specimen book of curious letters.",
    hero: ["A little type.", "A lot of cat."],
    intro:
      "Round shapes. Little ears.\nThe occasional curling tail.\nGive your everyday words a softer side.",
    try: "Try your own words",
    download: "Download the font",
    heroNote: "NIKUKYU MARU / にくきゅう丸",
    stamp: ["Free for", "creative work."],
    ribbon: ["Round.", "Soft.", "A little feline."],
    playground: "Make yourself at home.",
    playDesc: "Type a few words. Find a little personality.",
    input: "Text to preview",
    presets: ["A little catnap", "CAT & coffee", "Hiragana"],
    samples: [
      "A little catnap.\nCozy, curious letters.",
      "Cozy cat cafe\nA little purr, a little joy.",
      "にくきゅうまる\nあいうえお かきくけこ",
    ],
    size: "Type size",
    spacing: "Letter spacing",
    color: "Ink color",
    colors: ["Cocoa", "Vermilion", "Forest"],
    alternates: "Paw alternates for こ / る",
    reset: "Reset",
    privacy: "Your words stay in this browser. No text is sent anywhere.",
    empty: "Your words belong here.",
    missing: "Not included in this font (shown with a fallback):",
    features: ["Little ears.", "A curious tail.", "Secret little paws."],
    featureDescriptions: [
      "Plump shapes and broad, rounded ears. A feline feeling built into the letters.",
      "A curl at the end of a stroke. A different personality in every letter.",
      "Look inside a, or turn on the special paw alternates for こ and る.",
    ],
    glyphTitle: "Meet the little characters.",
    glyphDesc:
      "Latin, kana, kanji, and more. 7,516 Unicode characters for expressive headlines.",
    categories: ["Latin", "Hiragana", "Katakana", "Kanji", "Other", "All"],
    search: "Find a character",
    searchPlaceholder: "Type a character: A ね 猫",
    noGlyph: "No included characters match your search.",
    more: "Show more",
    shown: "characters shown",
    allChars: "See the complete character list",
    usesTitle: "A little charm goes a long way.",
    usesDesc:
      "Cafe menus, little packages, and big announcements. Give these letters some room to be themselves.",
    useLabels: ["01 / MENU", "02 / PACKAGE", "03 / POSTER"],
    storyLabel: "THE MAKING OF",
    storyTitle: "From a picture of letters\nto letters you can use.",
    story:
      "An image-generated cat alphabet became editable outlines, one character at a time. We compared the real font with its reference to refine every ear, tail, and curve. Japanese glyphs build on Mochiy Pop One and Zen Maru Gothic.",
    storyLink: "Compare the concept and the real font",
    downloadTitle: "Let a little cat\ninto your words.",
    downloadDesc:
      "Free to download. For personal and commercial creative work.",
    formats: ["For your computer", "For your website", "For your workbench"],
    formatDesc: [
      "A TTF font to install on Windows or macOS.",
      "A WOFF2 font to embed in your website.",
      "Editable UFO sources, reference images, and verification records.",
    ],
    howTitle: "A few things before you go.",
    faqs: [
      [
        "How do I install it?",
        "Download and open the TTF. Choose Install on Windows, or add it with Font Book on macOS. Restart any design apps that were already open.",
      ],
      [
        "Can I use it commercially?",
        "Yes. The font uses the SIL Open Font License 1.1. You can use it in commercial creative work and embed it on the web. You cannot sell the font by itself. Include its copyright notice and license when redistributing the font.",
      ],
      [
        "Where does it work best?",
        "Bold horizontal headlines. Try 32px or larger to enjoy the ears and paws. Small body text and vertical typesetting are not its strengths. Kerning, hinting, and dedicated vertical metrics are not implemented.",
      ],
      [
        "How do I use it on the web?",
        "Place the WOFF2 on your site and use the CSS below. The font weight is 800. Enable ss01 to use paw alternates for こ and る.",
      ],
    ],
    copyCss: "Copy CSS",
    copied: "Copied",
    copyFail: "Could not copy. Select and copy the code instead.",
    license: "Read the license",
    source: "Source & process",
    footer: "Round letters. Softer days.",
    loading: "Waking up the letters…",
    failed: "The font could not load. Please reload this page.",
    metadataFailed: "The character list could not load. Please try reloading.",
    back: "Back to the start",
    unavailable: "Page not found",
    errorText: "A curious cat may have carried this page away.",
  },
};
